export const data = [
  {
    rank: 10,
    track_name: 'The Life Of Prince - Maayunnallo (From "Prince And Family")',
    image_url:
      "https://i.scdn.co/image/ab67616d00001e0259e1825c44aa2596a8f4165c",
    artists: ["Sanal Dev", "Jakes Bejoy", "Titto P Thankachen"],
    track_url: "https://open.spotify.com/track/35KeXqFpfNPBOSh7n64djz",
    details: {
      "Release Date": "May 6, 2025",
      "First entry date": "May 22, 2025",
      "First entry position": "18",
      "Total weeks on chart": "8",
      Producers: "Al Nishad",
      Songwriters: "Sanal Dev, Titto P Thankachan",
      Source: "Magic Frames Music",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 20,
    track_name: "Vedakk Chekka",
    image_url:
      "https://i.scdn.co/image/ab67616d00001e0295513ef5b539a5254b18585d",
    artists: ["ThudWiser", "ItsPc", "MUSLI"],
    track_url: "https://open.spotify.com/track/0PGJHryop4kfDskuNmNnEn",
    details: {
      "Release Date": "Feb 25, 2025",
      "First entry date": "Mar 13, 2025",
      "First entry position": "18",
      "Total weeks on chart": "21",
      Producers: "ThudWiser",
      Songwriters: "ItsPc, MUSLI, ThudWiser",
      Source: "Universal Music India Pvt Ltd.",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 30,
    track_name: "Folkstep",
    image_url:
      "https://i.scdn.co/image/ab67616d00001e0221cd12cfd2a5996ee0ddfe02",
    artists: ["Sawhneyboi"],
    track_url: "https://open.spotify.com/track/1euRQs31L8qcXSp71blEje",
    details: {
      "Release Date": "Apr 16, 2025",
      "First entry date": "Jul 3, 2025",
      "First entry position": "71",
      "Total weeks on chart": "5",
      Producers: "",
      Songwriters: "Karan Sawhney",
      Source: "Sawhneyboi Music",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 40,
    track_name: "Thenpalani Kovil",
    image_url:
      "https://i.scdn.co/image/ab67616d00001e02f3a6b4f0733802c511189511",
    artists: ["Vaikom Vijayalakshmi"],
    track_url: "https://open.spotify.com/track/0f7DD832Vd25JzeriYUZCw",
    details: {
      "Release Date": "Feb 10, 2025",
      "First entry date": "May 29, 2025",
      "First entry position": "31",
      "Total weeks on chart": "10",
      Producers: "",
      Songwriters: "Kannan Mangalath, Shaiju Avaran",
      Source: "M C Digital",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 50,
    track_name: "Panthalchant",
    image_url:
      "https://i.scdn.co/image/ab67616d00001e02ef66218e47dd404201bf60a7",
    artists: ["Mu.Ri", "Dabzee", "JOKER390P", "M.H.R", "Wraith V", "BABY JEAN"],
    track_url: "https://open.spotify.com/track/7vGaqYx2lUN6Iaue5Q6PAc",
    details: {
      "Release Date": "Sep 6, 2024",
      "First entry date": "Sep 12, 2024",
      "First entry position": "3",
      "Total weeks on chart": "47",
      Producers: "",
      Songwriters:
        "Fazin Rasheed, Habish Rahman, M.H.R, Muhammed Fasil NV, Muhsin Parari, Wraith V",
      Source: "The Writing Company",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 60,
    track_name: "Dilshad",
    image_url:
      "https://i.scdn.co/image/ab67616d00001e02412c297adbd0a057a79eb0dc",
    artists: ["Yawar Abdal", "Sifar"],
    track_url: "https://open.spotify.com/track/487NdFWy4ie4r5xb0avzKw",
    details: {
      "Release Date": "Nov 27, 2024",
      "First entry date": "Jan 23, 2025",
      "First entry position": "98",
      "Total weeks on chart": "28",
      Producers: "Akash Gupta",
      Songwriters: "Yawar Abdal",
      Source: "Universal Music India Pvt Ltd.",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 70,
    track_name: 'K For Krishna (From "Guruvayoorambala Nadayil")',
    image_url:
      "https://i.scdn.co/image/ab67616d00001e025bd50cd18c9da9a3e7876912",
    artists: ["Aju Varghese", "Vinayak Sasikumar", "Ankit Menon"],
    track_url: "https://open.spotify.com/track/5ev5pWLaCzM6LaO9bVr7Vb",
    details: {
      "Release Date": "May 5, 2024",
      "First entry date": "May 9, 2024",
      "First entry position": "35",
      "Total weeks on chart": "65",
      Producers: "",
      Songwriters: "Ankit Menon, Vinayak Sasikumar",
      Source: "Saregama India Ltd",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 80,
    track_name: 'Hey Penne - From "Haal"',
    image_url:
      "https://i.scdn.co/image/ab67616d00001e02707bc847ff2bc3ace0fefb20",
    artists: ["Nandhagopan V", "Adithya RK", "Vinayak Sasikumar"],
    track_url: "https://open.spotify.com/track/0bBZk1Lby6kKzYKPyERtr6",
    details: {
      "Release Date": "Mar 14, 2025",
      "First entry date": "Mar 27, 2025",
      "First entry position": "58",
      "Total weeks on chart": "17",
      Producers: "",
      Songwriters: "Nandhagopan V, Vinayak Sasikumar",
      Source: "Think Music",
    },
    scraped_Date: "06-August-2025",
    city: "Delhi",
  },
  {
    rank: 90,
    track_name: 'Sana - Aaro Nee - From "Think Specials"',
    image_url:
      "https://i.scdn.co/image/ab67616d00001e026d320206a4a6cf1aa64d29c5",
    artists: ["Sharan Rajamohanan", "Anand Sankar"],
    track_url: "https://open.spotify.com/track/3sFi34K2RKSTqEFLQ7HVLl",
    details: {
      "Release Date": "Feb 26, 2024",
      "First entry date": "Mar 7, 2024",
      "First entry position": "80",
      "Total weeks on chart": "47",
      Producers: "",
      Songwriters: "Anand Sankar, Sharan Rajamohanan",
      Source: "Think Music",
    },
    scraped_Date: "06-August-2025",
    city: "kochi",
  },
  {
    rank: 100,
    track_name: "Modi Cheyyanumaru - Trending",
    image_url:
      "https://i.scdn.co/image/ab67616d00001e0245bf561298a1d33f17e3494c",
    artists: ["Abhidcruez", "Bheeshma Kochi"],
    track_url: "https://open.spotify.com/track/2uGLdYzaKDi9y04oI2X3Pj",
    details: {
      "Release Date": "May 16, 2025",
      "First entry date": "Jul 24, 2025",
      "First entry position": "99",
      "Total weeks on chart": "2",
      Producers: "",
      Songwriters: "Bheeshma Kochi",
      Source: "ANYONE RECORDS",
    },
    scraped_Date: "06-August-2025",
    city: "kolkata",
  },
];

